spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:boracodardevs}:${DB_PASSWORD:programacaoreativa}@programacaoreativaclust.lvecuyh.mongodb.net/programacaoreativa?retryWrites=true&w=majority
