spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:boracodardevs}:${DB_PASSWORD:boracodardevs}@programacaoreativaclust.lvecuyh.mongodb.net/programacaoreativa?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: "programacao-reativa"